import { StyleSheet } from 'react-native';

export const colors = {ink: '#22271F', muted: '#76816D', lime: '#C8ED69', pale: '#F2F9E6', white: '#FFFFFF', line: '#E3EBD9', red: '#AD543B'};
export const styles = StyleSheet.create({
  fill: {flex: 1},
  screen: {flex: 1, backgroundColor: colors.pale},
  body: {fontFamily: 'DM', color: colors.ink, fontSize: 12},
  muted: {fontFamily: 'DM', color: colors.muted, fontSize: 11, lineHeight: 17},
  title: {fontFamily: 'Barlow', fontSize: 25, color: colors.ink},
  heading: {fontFamily: 'BarlowMedium', fontSize: 20, color: colors.ink},
  number: {fontFamily: 'Barlow', fontSize: 31, color: colors.ink},
  row: {flexDirection: 'row', alignItems: 'center'},
  between: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  content: {paddingHorizontal: 22, paddingTop: 12, paddingBottom: 114, gap: 20},
  header: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 2},
  avatar: {width: 42, height: 42, borderRadius: 21, backgroundColor: colors.ink, justifyContent: 'center', alignItems: 'center'},
  avatarText: {fontFamily: 'Barlow', color: colors.lime, fontSize: 24},
  circle: {width: 42, height: 42, borderRadius: 21, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center'},
  section: {backgroundColor: colors.white, borderRadius: 23, padding: 17, gap: 13},
  divider: {height: 1, backgroundColor: '#EEF1E9'},
  mini: {fontFamily: 'DM', fontSize: 10, color: colors.muted},
  tag: {paddingVertical: 6, paddingHorizontal: 10, backgroundColor: colors.lime, borderRadius: 20},
  tagText: {fontFamily: 'DMMedium', fontSize: 10, color: colors.ink},
  card: {paddingTop: 16, paddingBottom: 24, paddingLeft: 22, paddingRight: 72, minHeight: 240, backgroundColor: 'transparent', position: 'relative'},
  cardLabel: {fontFamily: 'DM', fontSize: 11, color: '#B5BDAA'},
  cardBalance: {fontFamily: 'Barlow', fontSize: 37, color: colors.white, marginTop: 2},
  cardName: {fontFamily: 'DMMedium', fontSize: 12, color: colors.white},
  cardStripe: {position: 'absolute', right: 12, top: 54, bottom: 18, width: 44, borderRadius: 14, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center'},
  cardAturDana: {position: 'absolute', top: 2, right: 0, backgroundColor: colors.lime, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, flexDirection: 'row', gap: 6, alignItems: 'center'},
  cardAturDanaText: {fontFamily: 'BarlowMedium', fontSize: 12, color: colors.ink},
  cardAturDanaPlus: {backgroundColor: colors.ink, width: 16, height: 16, borderRadius: 8, alignItems: 'center', justifyContent: 'center'},
  cardChip: {width: 30, height: 22, borderRadius: 5, borderWidth: 1, borderColor: colors.lime + '66', backgroundColor: colors.lime + '1F', alignItems: 'center', justifyContent: 'center'},
  shortcut: {alignItems: 'center', width: '23%', gap: 7},
  shortcutCircle: {width: 58, height: 58, borderRadius: 29, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center'},
  actionLabel: {fontFamily: 'DMMedium', color: colors.ink, fontSize: 11, textAlign: 'center'},
  needIcon: {width: 37, height: 37, borderRadius: 19, backgroundColor: colors.pale, alignItems: 'center', justifyContent: 'center'},
  progress: {height: 5, borderRadius: 5, backgroundColor: '#EAF0E1', overflow: 'hidden'},
  progressFill: {height: '100%', borderRadius: 5, backgroundColor: colors.lime},
  listTitle: {fontFamily: 'DMMedium', color: colors.ink, fontSize: 12},
  amount: {fontFamily: 'BarlowMedium', fontSize: 18, color: colors.ink},
  notice: {padding: 15, borderRadius: 18, backgroundColor: '#E4F1CA', flexDirection: 'row', gap: 11},
  noticeTitle: {fontFamily: 'DMMedium', color: colors.ink, fontSize: 12, marginBottom: 4},
  navWrap: {position: 'absolute', bottom: 16, left: 20, right: 20, alignItems: 'center'},
  nav: {height: 60, paddingHorizontal: 10, borderRadius: 40, backgroundColor: colors.ink, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: 260, shadowColor: '#000', shadowOffset: {width: 0, height: 6}, shadowOpacity: .25, shadowRadius: 12, elevation: 8},
  navItem: {width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center'},
  navPlus: {backgroundColor: colors.lime, width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center'},
  modalBackdrop: {flex: 1, backgroundColor: '#11170CAC', justifyContent: 'flex-end'},
  modal: {backgroundColor: colors.pale, borderTopLeftRadius: 29, borderTopRightRadius: 29, padding: 23, paddingBottom: 28, maxHeight: '91%'},
  input: {borderWidth: 1, borderColor: '#DEE6D5', borderRadius: 14, backgroundColor: '#FFFFFF', paddingHorizontal: 15, paddingVertical: 12, fontFamily: 'DM', fontSize: 14, color: colors.ink, minHeight: 48},
  field: {gap: 7, marginTop: 16},
  fieldLabel: {fontFamily: 'DMMedium', fontSize: 11, color: colors.muted},
  button: {backgroundColor: colors.ink, minHeight: 49, paddingHorizontal: 19, borderRadius: 26, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 9},
  buttonText: {fontFamily: 'DMMedium', color: colors.white, fontSize: 12},
  secondaryButton: {backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line},
  tab: {paddingVertical: 11, paddingHorizontal: 16, borderRadius: 22, backgroundColor: colors.white},
  tabActive: {backgroundColor: colors.lime},
  error: {fontFamily: 'DM', color: colors.red, fontSize: 12, lineHeight: 18, marginTop: 13},
  empty: {padding: 20, alignItems: 'center', gap: 10},
  tinyButton: {paddingHorizontal: 12, paddingVertical: 9, backgroundColor: colors.pale, borderRadius: 18},
  welcome: {flex: 1, backgroundColor: colors.lime, padding: 26, justifyContent: 'space-between'},
  welcomeTitle: {fontFamily: 'Barlow', fontSize: 51, lineHeight: 52, color: colors.ink},
  day: {width: '12.5%', height: 44, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginBottom: 4},
  stat: {flex: 1, backgroundColor: colors.lime, borderRadius: 21, padding: 17, minHeight: 146, gap: 7},
});
